# Generated by Django 4.0.4 on 2022-08-28 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
