# Generated by Django 4.0.4 on 2022-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_status_mood_status_mood_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='mood_image',
            new_name='mood_icon',
        ),
    ]
