# Generated by Django 4.0.4 on 2022-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_mood_image_status_mood_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='mood_icon',
            field=models.ImageField(default='neutral.png', upload_to='mood_pictures'),
        ),
    ]
