# Generated by Django 4.0.4 on 2022-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_created_at_alter_status_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='hugs',
            field=models.IntegerField(default=0),
        ),
    ]
